//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chanyi.Shepherd.WPF.ProductService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.IQueryService")]
    public interface IQueryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryService/GetProductLatestVersion", ReplyAction="http://tempuri.org/IQueryService/GetProductLatestVersionResponse")]
        string GetProductLatestVersion(string productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryService/IsTryoutTimeout", ReplyAction="http://tempuri.org/IQueryService/IsTryoutTimeoutResponse")]
        bool IsTryoutTimeout(string phoneNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueryServiceChannel : Chanyi.Shepherd.WPF.ProductService.IQueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryServiceClient : System.ServiceModel.ClientBase<Chanyi.Shepherd.WPF.ProductService.IQueryService>, Chanyi.Shepherd.WPF.ProductService.IQueryService {
        
        public QueryServiceClient() {
        }
        
        public QueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetProductLatestVersion(string productId) {
            return base.Channel.GetProductLatestVersion(productId);
        }
        
        public bool IsTryoutTimeout(string phoneNum) {
            return base.Channel.IsTryoutTimeout(phoneNum);
        }
    }
}
