//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chanyi.Web.Official.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResultOfstring", Namespace="http://schemas.datacontract.org/2004/07/Chanyi.DomainModel.Service")]
    [System.SerializableAttribute()]
    public partial class ServiceResultOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Chanyi.Web.Official.ProductService.ResultStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Chanyi.Web.Official.ProductService.ResultStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultStatus", Namespace="http://schemas.datacontract.org/2004/07/Chanyi.DomainModel.Service")]
    public enum ResultStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WANING = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 99,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.IManageService")]
    public interface IManageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageService/CreateCustomer", ReplyAction="http://tempuri.org/IManageService/CreateCustomerResponse")]
        Chanyi.Web.Official.ProductService.ServiceResultOfstring CreateCustomer(string Department, string Scale, string ContactPerson, string PhoneNumber, string Address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageService/CreateCustomer", ReplyAction="http://tempuri.org/IManageService/CreateCustomerResponse")]
        System.Threading.Tasks.Task<Chanyi.Web.Official.ProductService.ServiceResultOfstring> CreateCustomerAsync(string Department, string Scale, string ContactPerson, string PhoneNumber, string Address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageService/CreateCustomerTryout", ReplyAction="http://tempuri.org/IManageService/CreateCustomerTryoutResponse")]
        Chanyi.Web.Official.ProductService.ServiceResultOfstring CreateCustomerTryout(string Department, string Scale, string ContactPerson, string PhoneNumber, string Address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageService/CreateCustomerTryout", ReplyAction="http://tempuri.org/IManageService/CreateCustomerTryoutResponse")]
        System.Threading.Tasks.Task<Chanyi.Web.Official.ProductService.ServiceResultOfstring> CreateCustomerTryoutAsync(string Department, string Scale, string ContactPerson, string PhoneNumber, string Address);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManageServiceChannel : Chanyi.Web.Official.ProductService.IManageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageServiceClient : System.ServiceModel.ClientBase<Chanyi.Web.Official.ProductService.IManageService>, Chanyi.Web.Official.ProductService.IManageService {
        
        public ManageServiceClient() {
        }
        
        public ManageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Chanyi.Web.Official.ProductService.ServiceResultOfstring CreateCustomer(string Department, string Scale, string ContactPerson, string PhoneNumber, string Address) {
            return base.Channel.CreateCustomer(Department, Scale, ContactPerson, PhoneNumber, Address);
        }
        
        public System.Threading.Tasks.Task<Chanyi.Web.Official.ProductService.ServiceResultOfstring> CreateCustomerAsync(string Department, string Scale, string ContactPerson, string PhoneNumber, string Address) {
            return base.Channel.CreateCustomerAsync(Department, Scale, ContactPerson, PhoneNumber, Address);
        }
        
        public Chanyi.Web.Official.ProductService.ServiceResultOfstring CreateCustomerTryout(string Department, string Scale, string ContactPerson, string PhoneNumber, string Address) {
            return base.Channel.CreateCustomerTryout(Department, Scale, ContactPerson, PhoneNumber, Address);
        }
        
        public System.Threading.Tasks.Task<Chanyi.Web.Official.ProductService.ServiceResultOfstring> CreateCustomerTryoutAsync(string Department, string Scale, string ContactPerson, string PhoneNumber, string Address) {
            return base.Channel.CreateCustomerTryoutAsync(Department, Scale, ContactPerson, PhoneNumber, Address);
        }
    }
}
